# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "centos65"

  config.vm.network :forwarded_port, guest: 5432, host: 65432

  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "../config/puppet/manifests"
    puppet.manifest_file  = "site.pp"
    puppet.module_path = [ "../config/puppet/modules", "../config/puppet/forge" ]
    puppet.options  = ""
  end

end
